name: geSuitWarps
main: net.cubespace.geSuitWarps.geSuitWarps
version: ${project.version}b-${build.number}
description: Part of the gesuit this plugin allows users to warp to certain points.
author: geNAZt
depend: [geSuitTeleports]
commands:
    warps:
        description: Shows a list of available warps.
        aliases: [warplist]
        permission: gesuit.warps.command.warps
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    warp:
        description: Warps a player to a specific warp.
        aliases: [warpto]
        permission: gesuit.warps.command.warp
        permission-message: §cYou do not have permission for this command
        usage: /<command> (warp name)
    setwarp:
        description: Sets a warps at the players location.
        permission: gesuit.warps.command.setwarp
        permission-message: §cYou do not have permission for this command
        usage: |
            /<command> - sets a warp for the current server
            /<command> (hidden true/false) - sets a hidden warp
            /<command> (hidden) (global true/false) - sets a global warp
        aliases: [createwarp]
    delwarp:
        description: Used to delete a specific warp
        permission: gesuit.warps.command.delwarp
        permission-message: §cYou do not have permission for this command
        usage: /<command> (warp name)
        aliases: [deletewarp, removewarp]
        
permissions:
    gesuit.warps.*:
        description: Gives access to all gesuitWarps commands
        default: op
        children:
            gesuit.warps.admin: true
    gesuit.warps.admin:
        description: Gives access to all gesuitWarps admin commands
        children:
            gesuit.warps.user: true
            gesuit.warps.command.setwarp: true
            gesuit.warps.command.delwarp: true
            gesuit.warps.list.hidden: true
            gesuit.warps.warp.*: true
            gesuit.warps.bypass: true
            gesuit.warps.command.warp.other: true
    gesuit.warps.user:
        description: Gives access to all gesuitWarps user commands
        children:
            gesuit.warps.command.warps: true
            gesuit.warps.command.warp: true
            gesuit.warps.list.server: true
            gesuit.warps.list.global: true
    gesuit.warps.list.hidden:
        description: Displays all hidden warps to the user
    gesuit.warps.list.server:
        description: Displays all server warps to the user
    gesuit.warps.list.global:
        description: Displays all global warps to the user
    gesuit.warps.warp.*:
        description: Allows access to all warps
    gesuit.warps.warp.<warpname>:
        description: "allows access to <warpname>"
    gesuit.warps.bypass:
        description: Allows players to user perserver warps cross server
    gesuit.warps.command.warp.other:
        description: Allows players to warp other players
